controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_process_message:
    path: /api/process-message
    controller: App\Controller\ApiController::processMessage
    methods: [POST]